Numpy

# Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange

In [7]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

# zeros & ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# linspace

In [13]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

# eye

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# rand

In [15]:
np.random.rand(2)

array([0.03438641, 0.51452165])

In [16]:
np.random.rand(5,5)

array([[0.5383211 , 0.67919669, 0.90610165, 0.63074293, 0.70251221],
       [0.36231359, 0.35914995, 0.21865463, 0.50539278, 0.42866095],
       [0.71454324, 0.65876866, 0.10153959, 0.84690399, 0.31956033],
       [0.10923773, 0.10179982, 0.95920264, 0.7079635 , 0.26756449],
       [0.21339397, 0.36393264, 0.75511808, 0.98083037, 0.37475243]])

# randn

In [17]:
np.random.randn(2)

array([-1.0679812 , -0.51845469])

In [18]:
np.random.randn(5,5)

array([[-0.04077516,  0.85108949,  1.66533207,  0.28591789,  2.29454695],
       [-0.44145808,  1.30598764,  0.11618587,  1.16562374,  2.128144  ],
       [-0.52902952,  0.57803285, -0.25386623, -0.11240279, -0.85162505],
       [ 1.72310891,  0.5415404 ,  0.01745218,  1.52012053, -0.40546842],
       [-0.16094752,  0.07404666,  0.14740449, -0.72595562,  0.1166003 ]])

In [19]:
np.random.randn(3,5)

array([[-0.72437955,  2.17904609, -0.27262565,  0.44506912, -0.40296114],
       [-0.13416419, -0.95772394,  0.89570934,  1.28636776,  0.10235875],
       [-0.67317892,  0.45131873, -0.63997904, -0.86437057,  0.82099787]])

# randint

In [20]:
np.random.randint(1,5)

2

In [21]:
np.random.randint(1, 100, 12)

array([12, 91, 53, 21, 11, 54, 13, 16, 23, 58, 80, 97])

Array Attributes and method

In [22]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# shape & reshape 

In [24]:
arr.shape

(25,)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# flatten

In [26]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

# min - max - argmin - argmax

In [27]:
rand_arr = np.random.randint(0,50,10)
rand_arr

array([26, 32, 20, 25,  8, 28, 45, 28, 20, 24])

In [28]:
rand_arr.min()

8

In [29]:
rand_arr.argmin()

4

In [30]:
rand_arr.max()

45

In [31]:
rand_arr.argmax()

6

In [32]:
arr_2 = np.random.randn(5,5)
arr_2.shape

(5, 5)

# flatten

In [33]:
v = arr_2.flatten()
v

array([-0.29771065,  0.28477902, -0.50787074, -1.08367808, -0.76711671,
       -2.40962244,  0.16706109, -0.66600028,  2.21554872,  0.01211149,
        1.81235491,  1.13002928,  0.1580548 ,  0.32539269,  1.13207703,
        1.01924956, -0.04919187, -0.77289484,  1.42695485, -0.65593349,
       -0.47559576,  0.72494043, -1.53221262,  0.89053593, -0.37644198])

In [34]:
v.shape

(25,)

In [35]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

# vstack & hstack

In [36]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# concatenate

In [38]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [39]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Numpy Indexing and Selection

In [40]:
arr_3 = np.arange(0, 11)
arr_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# bracket Indexing , Slicing

In [41]:
arr_3[0]

0

In [42]:
arr_3[1]

1

In [43]:
arr_3[-1]

10

In [44]:
arr_3[0:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [45]:
arr_3[1:7]

array([1, 2, 3, 4, 5, 6])

In [46]:
arr_3[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr_3[0:7:2]

array([0, 2, 4, 6])

In [48]:
arr_3[::2]

array([ 0,  2,  4,  6,  8, 10])

In [49]:
arr_3[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Broadcasting

In [50]:
arr_3[0:5] = 100
arr_3

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr_4 = np.arange(0, 15)
arr_4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
slice_array = arr_4[0:6]
slice_array

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_array[:] = 99
slice_array

array([99, 99, 99, 99, 99, 99])

In [54]:
arr_4

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Copy

In [55]:
arr_5 = np.arange(0, 11)
arr_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr_5.copy()[0:6]
arr_copy

array([0, 1, 2, 3, 4, 5])

In [57]:
arr_copy[:] = 99
arr_copy

array([99, 99, 99, 99, 99, 99])

In [58]:
arr_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# indexing a 2D array (Matrices)

In [59]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d[1]

array([20, 25, 30])

In [61]:
arr_2d[2][0]

35

In [62]:
arr_2d[0][:2]

array([ 5, 10])

In [63]:
arr_2d[0][0]

5

In [64]:
arr_2d.transpose()

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [65]:
mat = np.arange(1, 101).reshape(10,10)
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [66]:
mat[0:5]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [67]:
mat[3:]

array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [68]:
mat[3:][0]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [69]:
mat[3:,5:]

array([[ 36,  37,  38,  39,  40],
       [ 46,  47,  48,  49,  50],
       [ 56,  57,  58,  59,  60],
       [ 66,  67,  68,  69,  70],
       [ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [70]:
mat[3:,5:][0,2]

38

In [71]:
mat[3:,5:][0][2]

38

In [72]:
mat[0:2, 0:2]

array([[ 1,  2],
       [11, 12]])

# Fancy Indexing

In [73]:
mat[2:5]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [74]:
mat[[2,4]]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [75]:
mat[[2,4], 3:6]

array([[24, 25, 26],
       [44, 45, 46]])

# Both Dimension Fancy Indexing

In [76]:
mat[[1,5],:][:,[3,5,7]]

array([[14, 16, 18],
       [54, 56, 58]])

# selection

In [77]:
arr_6 = np.arange(1, 11)
arr_6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr_6 > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [79]:
arr_6 == 3

array([False, False,  True, False, False, False, False, False, False,
       False])

In [80]:
bool_arr = arr_6 > 4
arr_6[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr_6[arr_6 > 4]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr_6[arr_6 == 2]

array([2])

In [83]:
arr_6[arr_6 <= 5]

array([1, 2, 3, 4, 5])

In [84]:
arr_6[arr_6%2 == 0]

array([ 2,  4,  6,  8, 10])

# Numpy operation (Array with Array (Arithmetic))

In [85]:
arr_7 = np.arange(0, 10)
arr_7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr_7 + arr_7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [87]:
arr_7 * arr_7

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [88]:
arr_7 ** arr_7

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [89]:
arr_7 / arr_7

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_8796\1230566327.py:1: RuntimeWarning: invalid value encountered in divide
  arr_7 / arr_7


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# array with Scalar

In [90]:
arr_7 * arr_7

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [91]:
arr_7 ** arr_7

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [92]:
arr_7 - arr_7

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
arr_7 / arr_7

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_8796\1230566327.py:1: RuntimeWarning: invalid value encountered in divide
  arr_7 / arr_7


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

# Universal Array Functions

In [96]:
arr_7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.sqrt(arr_7)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [98]:
np.exp(arr_7)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [99]:
np.max(arr_7)

9

In [100]:
np.min(arr_7)

0

In [101]:
np.log(arr_7)

C:\Users\ziggurat\AppData\Local\Temp\ipykernel_8796\3650133426.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr_7)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [102]:
np.sin(arr_7)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [103]:
np.cos(arr_7)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

# Method

In [104]:
mat_1 = np.arange(1, 101).reshape(10,10)
mat_1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [105]:
np.triu(mat_1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  0,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  0,   0,  23,  24,  25,  26,  27,  28,  29,  30],
       [  0,   0,   0,  34,  35,  36,  37,  38,  39,  40],
       [  0,   0,   0,   0,  45,  46,  47,  48,  49,  50],
       [  0,   0,   0,   0,   0,  56,  57,  58,  59,  60],
       [  0,   0,   0,   0,   0,   0,  67,  68,  69,  70],
       [  0,   0,   0,   0,   0,   0,   0,  78,  79,  80],
       [  0,   0,   0,   0,   0,   0,   0,   0,  89,  90],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0, 100]])

In [106]:
np.tril(mat_1)

array([[  1,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 11,  12,   0,   0,   0,   0,   0,   0,   0,   0],
       [ 21,  22,  23,   0,   0,   0,   0,   0,   0,   0],
       [ 31,  32,  33,  34,   0,   0,   0,   0,   0,   0],
       [ 41,  42,  43,  44,  45,   0,   0,   0,   0,   0],
       [ 51,  52,  53,  54,  55,  56,   0,   0,   0,   0],
       [ 61,  62,  63,  64,  65,  66,  67,   0,   0,   0],
       [ 71,  72,  73,  74,  75,  76,  77,  78,   0,   0],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,   0],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [107]:
np.where(mat_1 < 50, mat_1, mat_1*10)

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22,   23,   24,   25,   26,   27,   28,   29,   30],
       [  31,   32,   33,   34,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,  500],
       [ 510,  520,  530,  540,  550,  560,  570,  580,  590,  600],
       [ 610,  620,  630,  640,  650,  660,  670,  680,  690,  700],
       [ 710,  720,  730,  740,  750,  760,  770,  780,  790,  800],
       [ 810,  820,  830,  840,  850,  860,  870,  880,  890,  900],
       [ 910,  920,  930,  940,  950,  960,  970,  980,  990, 1000]])

In [108]:
np.where(mat_1 > 50, mat_1, mat_1*10)

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250, 260, 270, 280, 290, 300],
       [310, 320, 330, 340, 350, 360, 370, 380, 390, 400],
       [410, 420, 430, 440, 450, 460, 470, 480, 490, 500],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])